# Python

* Целая куча упражнений на типы данных\операторы и функции

https://www.w3resource.com/python-exercises/

Типы данных:
* Числа (7382, 3.14, 3+4j, Decimal, Fraction)
* Строки ('net', "your's", u'радость')
* Списки ([1, [2, 'three'], 4])
* Словари ({'Alex': 2, 'Brian': 4})
* Кортежи ('Leo', 21.7, 'single')
* Множества (set(1,2,3), {'a', 'b', 'c'})
* Файлы (open('myfile', 'r'))

1. Склеить 3 подстроки "ada", "lovelace", "was considered the world's first computer programmer.". Первые две строки сделать с большой буквы.  (★☆☆)


In [266]:
input = ["ada", "lovelace", "was considered the world's first computer programmer."]

" ".join(map(lambda x, i: x.capitalize() if i < 2 else x, input, range(len(input))))

"Ada Lovelace was considered the world's first computer programmer."

2. Удаление лишних пробельных символов справа, слева, с обоих сторон  (☆☆☆)

In [267]:
input = "    ada    "

output1 = input.rstrip()
output2 = input.lstrip()
output3 = input.strip()

(output1, output2, output3)

('    ada', 'ada    ', 'ada')

3. Найти первое вхождение в строку подстроки (☆☆☆)

In [268]:
s1="But if you stick with me, I’m gonna accomplish great things, Morty, and you’re gonna be part of ’em."
s2="you"

s1.find(s2)

7

* isdigit - состоит ли строка из цифр;
* isalpha - состоит ли строка из букв;
* isalnum - состоит ли строка из цифр или букв;
* islower - состоит ли строка из символов в нижнем регистре;
* isupper - состоит ли строка из символов в верхнем регистре;
* istitle - начинаются ли слова в строке с заглавной буквы.

4. Разбить строку по разделителю (☆☆☆)

In [269]:
s1="Holy#cow,#Rick!#I#didn’t#know#hanging#out#with#you#was#making#me#smarter!"

output = s1.split("#")

output

['Holy',
 'cow,',
 'Rick!',
 'I',
 'didn’t',
 'know',
 'hanging',
 'out',
 'with',
 'you',
 'was',
 'making',
 'me',
 'smarter!']

5. Полученный массив строк склеить через пробел (★☆☆)

In [270]:
" ".join(output)

'Holy cow, Rick! I didn’t know hanging out with you was making me smarter!'

6. Вывести данные из словаря в три строки в виде "NAME (age AGE) is a JOB" (★☆☆)

(hint: .format())

In [271]:
personal_data = {1: ("Ann", 29, "Artist"), 
               2: ("Leo", 54, "Programmer"), 
               3: ("Tiffany", 43, "Shop Assistant")}

output = "\n".join(map(lambda x: "{0} (age {1}) is a {2}".format(*x), personal_data.values()))

print(output)

Ann (age 29) is a Artist
Leo (age 54) is a Programmer
Tiffany (age 43) is a Shop Assistant


7. Требуется определить, является ли данный год високосным. (год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.)  (★★☆)

Входные данные: Вводится единственное число - номер года (целое, положительное, не превышает 30000).

Выходные данные: Требуется вывести слово YES, если год является високосным и NO - в противном случае.

In [272]:
def is_leap_year(year: int):
  if year % 4 == 0 and year % 100 != 0 or year % 400 == 0:
    return "YES"
  else:
    return "NO"

years = [2000, 2005, 2020, 2022, 2100]

output = "\n".join(map(lambda year: f"{year} - {is_leap_year(year)}", years))

print(output)

2000 - YES
2005 - NO
2020 - YES
2022 - NO
2100 - NO


8. Закодируйте каждый элемент списка слов числом, результат сопоставления (слово-число) поместите в словарь.  (★☆☆)

In [273]:
words = ['Not', 'my', 'cup', 'of', 'tea']

{word: i for i,word in enumerate(words)}

{'Not': 0, 'my': 1, 'cup': 2, 'of': 3, 'tea': 4}

9. Удалить второй элемент из списка по индексу\по значению  (★☆☆)

In [274]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']

output1 = dogs.copy()
output2 = dogs.copy()

output1.pop(1)
output2.remove('australian cattle dog')

print(output1)
print(output2)

['border collie', 'labrador retriever']
['border collie', 'labrador retriever']


10. Вывести срез списка с 3 по 5 элемент включительно и все слова перевести в верхний регистр (★☆☆)

In [275]:
dogs = ['border', 'collie', 'australian', 'cattle', 'dog', 'labrador', 'retriever']

output = list(map(lambda dog: dog.upper(), dogs[2:5]))

output

['AUSTRALIAN', 'CATTLE', 'DOG']

11. Словарь словарей. Вывести из словаря для каждого питомца его имя, породу, имя владельца, и наличие прививки. Строку вывода формировать через .format() (★☆☆)

In [276]:
pets = {'willie': {'kind': 'dog', 'owner': 'eric', 'vaccinated': True},
        'walter': {'kind': 'cockroach', 'owner': 'eric', 'vaccinated': False},
        'peso': {'kind': 'dog', 'owner': 'chloe', 'vaccinated': True},
        }

output = "\n".join(map(lambda pet: "name: {0}, kind: {1[kind]}, vaccinated: {1[vaccinated]}, owner's name: {1[owner]}".format(*pet), pets.items()))

print(output)

name: willie, kind: dog, vaccinated: True, owner's name: eric
name: walter, kind: cockroach, vaccinated: False, owner's name: eric
name: peso, kind: dog, vaccinated: True, owner's name: chloe


12. Проверить является ли множество подмножеством другого множества  (★☆☆)

In [277]:
a=set([2, 5, 6])
b=set([2, 4, 8, 3, 5, 6])

a.issubset(b)

True

13. Объединить несколько множеств (★☆☆)

In [278]:
a=set([10, 35, 6, 5])
b=set([2, 4, 8, 3, 5, 6, 35])
c=set([4, 5, 35])

a.union(b).union(c)

{2, 3, 4, 5, 6, 8, 10, 35}

14. Посчитать пересечение множества b с остальными из предыдущего задания  (★★☆)

(hint: set.intersection(other, ...) (или set & other &) )

In [279]:
b.intersection(a, c)

{5, 35}

15. Вывести множество из элементов, встречающихся в одном множестве, но не встречающиеся в обоих. (★★☆)

(hint: .symmetric_difference())

In [280]:
a=set([1, 2, 3, 4, 5])
b=set([3, 4, 5, 6, 7])

a.symmetric_difference(b)

{1, 2, 6, 7}

16. Предположим, есть файл с данными клиентов. В качестве простого примера воьзьмем txt-файл(нужно создать файл с предложенным/другим содержанием самостоятельно) следующего содержания:

    lastname,age,debt,occupation
    
    Adrianov,25,30000,artist
    
    Нужно считать файл data/credit_sample.txt.
    Сделать словарь вида:
        {lastname: (age,debt,occupation)}
    
    Посчитать сколько уникальных профессий получилось в словаре.
    
    Результат записать в json (★★★)

In [281]:
import json

file = open("data/credit_sample.txt", "r")
keys = file.readline()
values = file.readlines()
file.close()

normalized_values = list(map(lambda line: line.replace('\n', '').split(','), values)) 
credit_data = {values[0]: (values[1], values[2], values[3]) for values in normalized_values}

output = set(map(lambda x: x[2], credit_data.values()))

json.dumps(list(output))

'["salesman", "artist", "president", "programmer"]'

### os, sys, datetime

17. Получить список файлов в папке gifs/ и оставить только файлы с расширением .gif (★★☆)

In [282]:
import os

file_names = os.listdir('./gifs')
output = list(filter(lambda name: name.split('.')[-1] == 'gif', file_names))

output

['1.gif', '3.gif']

18. Создать папку с названием temp и удалить её (★☆☆)

In [283]:
os.mkdir('temp')
print(f"directories: {','.join(os.listdir())}")
os.rmdir('temp')

directories: data,gifs,main.ipynb,temp


19. Вывести переменные среды (★☆☆)

(hint: environ)

In [284]:
os.environ.get('OS')

'Windows_NT'

20. Как игнорировать warrnings?

In [285]:
import warnings

def make_warning(): 
  warnings.warn('deprecated', DeprecationWarning)

warnings.filterwarnings("default")

make_warning()

warnings.filterwarnings("ignore")

make_warning()

C:\Users\nikit\AppData\Local\Temp\ipykernel_9012\3276538275.py:4: DeprecationWarning: deprecated
  warnings.warn('deprecated', DeprecationWarning)


* Про datetime и timedelta 

https://www.guru99.com/date-time-and-datetime-classes-in-python.html

21. Вывести сегодняшнюю, вчерашнюю и завтрашнюю дату (☆☆☆)

In [286]:
from datetime import date, datetime, timedelta

today = date.today()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

(today, yesterday, tomorrow)

(datetime.date(2022, 10, 30),
 datetime.date(2022, 10, 29),
 datetime.date(2022, 10, 31))

22. Вывести день недели сегодняшней даты (★☆☆)

In [287]:
date.today().strftime("%A")

'Sunday'

23. Получить список дат за предыдущую неделю (★★☆)

In [288]:
starting_last_week = date.today() - timedelta(days=date.today().weekday() + 7)

[starting_last_week + timedelta(days=i) for i in range(7)]

[datetime.date(2022, 10, 17),
 datetime.date(2022, 10, 18),
 datetime.date(2022, 10, 19),
 datetime.date(2022, 10, 20),
 datetime.date(2022, 10, 21),
 datetime.date(2022, 10, 22),
 datetime.date(2022, 10, 23)]

24. Вывести дату с часами и минутами, отформатировать в формате: 01.12.2019 00:12:54 (★★☆)
            
(hint: now().strftime())

In [289]:
datetime.now().strftime("%d.%m.%Y %H:%M:%S")

'30.10.2022 23:18:06'

25. Исходя из текущей даты вычислить дату предыдущего понедельника (★★★)

In [290]:
last_monday = date.today() - timedelta(days=date.today().weekday() + 7)
last_monday.strftime('Last %A %d.%m.%Y')

'Last Monday 17.10.2022'

# Numpy

### numpy в картинках (реально лучший):

https://jalammar.github.io/visual-numpy/

In [291]:
import numpy as np

1. Задать нулевой вектор размером 10 (★☆☆)

(hint: np.zeros)

In [292]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

2. Как найти размер занимаемой памяти любым массивом (★☆☆)

(hint: size, itemsize)

In [293]:
x = np.array([123, 45, 6])
f"Memory size: {x.size * x.itemsize}"

'Memory size: 12'

3. Создать вектор из 10 нулей, кроме пятого элемента, который равен 1 (★☆☆)

In [294]:
vector = np.zeros(10, dtype='int', )
vector[4] = 1
vector

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

4. Создать вектор от 10 до 50 включительно (★☆☆)

(hint:np.arange)

In [295]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

5. Перевернуть вектор (первый элемент будет последним) (★☆☆)

In [296]:
np.flip(np.arange(0, 100))

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

6. Создать матрицу 3х3 с элементами от 0 до 8 (★☆☆)

(hint: reshape)

In [297]:
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Найти индексы не нулевых эемелентов в numpy array [1,2,0,0,4,0] (★☆☆)

(hint: np.nonzero)

In [298]:
input = np.array([1,2,0,0,4,0])
input.nonzero()

(array([0, 1, 4], dtype=int64),)

8. Создать матрицу 10x10 array с рандомными числами и найти минимум, максимум и среднее (★☆☆)

In [299]:
input = np.random.randint(100, size=100)

min = input.min()
max = input.max()
average = input.mean()

f"min: {min}, max: {max}, average: {average}"

'min: 0, max: 99, average: 47.78'

9. Создать матрицу 8x8 и заполнить 0 и 1 в стиле шахматной доски (★☆☆)

(hint: array[::n])

In [300]:
np.row_stack(([[0,1] * 4], [[1,0] * 4]) * 4)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

10. Нормализовать рандомную матрицу 5x5 (★☆☆)

(hint: (x - mean) / std)

In [301]:
x = np.random.random((5,5))

x / x.sum(axis=1)[:,np.newaxis]

array([[0.21402857, 0.18220678, 0.16115346, 0.24249628, 0.20011492],
       [0.2240853 , 0.20049857, 0.21413184, 0.15597176, 0.20531253],
       [0.07550795, 0.27319292, 0.15272692, 0.22455164, 0.27402057],
       [0.03457204, 0.34394536, 0.21789534, 0.27870141, 0.12488586],
       [0.07103958, 0.31592284, 0.29841752, 0.10701546, 0.2076046 ]])

11. Найти общие элементы между двумя массивами

(hint: np.intersect1d)

In [302]:
input1 = np.random.randint(100, size=10)
input2 = np.random.randint(100, size=10)

print(input1)
print(input2)

np.intersect1d(input1, input2)

[84 67 43 78 10 37 33 20 19 47]
[51 70 13 44 65 28  3 61  7  5]


array([], dtype=int32)

12. Извлечь целую часть рандомного массива чисел различными способами (максимум 5) (★★☆)

In [303]:
input = np.random.random(5) * 100

print(f"original: {input}")

print(f"1) {input.round()}")
print(f"2) {np.around(input)}")
print(f"3) {np.rint(input)}")
print(f"4) {np.fix(input)}")
print(f"5) {np.floor(input)}")
print(f"6) {np.ceil(input)}")
print(f"7) {np.trunc(input)}")


original: [35.2411547  90.78270003 27.01028992 80.21761167 63.93873421]
1) [35. 91. 27. 80. 64.]
2) [35. 91. 27. 80. 64.]
3) [35. 91. 27. 80. 64.]
4) [35. 90. 27. 80. 63.]
5) [35. 90. 27. 80. 63.]
6) [36. 91. 28. 81. 64.]
7) [35. 90. 27. 80. 63.]


13. Создать рандомный вектор размера 10 и отсортировать его (★★☆)

In [304]:
input = np.random.randint(100, size=10)
input.sort()
input

array([13, 19, 24, 41, 58, 75, 75, 78, 79, 84])

14. Проверить одинаковы ли два рандомных массива А и B (★★☆)

(hint: np.allclose, np.array_equal)

In [305]:
input1 = np.random.randint(5, size=10)
input2 = np.random.randint(5, size=10)

print(input1)
print(input2)
print(f"isEqual = {np.array_equal(input1, input2)}")

[1 3 2 3 1 4 1 3 0 3]
[2 3 3 2 3 1 2 2 2 4]
isEqual = False


15. Создать рандомный ветор размером 10 и максимальный элемент заменить на -1 (★★☆)

(hint: argmax)

In [306]:
input = np.random.randint(10, size=10)
print(input)

input[input.argmax()] = -1
print(input)

[9 4 2 1 9 9 7 1 7 0]
[-1  4  2  1  9  9  7  1  7  0]


16. Найдите самый близкий элемент к данному рандомному числу в векторе? (★★☆)

(hint: argmin)

In [307]:
z = np.arange(100)
v = np.random.uniform(0,100)
index = np.argmin(np.abs(z - v))
print(z[index])

40


17. Посчитать среднее для каждой строки матрицы (★★☆)

In [308]:
input = np.random.randint(100, size=(5, 5))
print(input)
print(np.mean(input[:, :5], axis=1))

[[30 28  3 27 59]
 [20 51 70  8  6]
 [11 37  8 54 15]
 [80 82 44 38 68]
 [74 43  4  8 58]]
[29.4 31.  25.  62.4 37.4]


18. Посчитать среднее со скользящим окном над массивом (★★★)

(hint: np.cumsum)

In [309]:
input = np.random.randint(100, size=10)
size = 3
print(input)

cumsum = np.cumsum(np.insert(input, 0, 0)) 
output = (cumsum[size:] - cumsum[:-size]) / float(size)
output


[79 33 48  4 72 23 78 92 44 61]


array([53.33333333, 28.33333333, 41.33333333, 33.        , 57.66666667,
       64.33333333, 71.33333333, 65.66666667])

# Regular expressions

* Cупер статья на все времена. Особенно понятно все про такие сложные штуки как lookaround. 

https://habr.com/ru/post/349860/


* Задания на регулярки

https://regexone.com/

* На этом сайте удобно тестировать регулярку, которую мучаешь, можно написать несколько примеров и тестировать на них. Важно не забывать выбирать Python:

https://regex101.com/

1. Из строки в файле data/rejson.txt вытащить хэш. Пример:

'master_guid': '<b>233880bb4c50d247f84edc9cac9e6e29</b>_2308194320'

In [311]:
import re

file = open("data/rejson.txt", "r")
text_json = file.read()
file.close()

obj = json.loads(text_json)
master_guid = obj.get("master_guid")
hash = re.split('[_]', master_guid, maxsplit=1)[0]
hash

OSError: [Errno 22] Invalid argument: 'https://raw.githubusercontent.com/Todti-I/python-hw/main/homework-1/data.csv'

# Pandas

* Pandas в картинках

https://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas/

* 10 minutes to pandas

https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

* 🐼реально классный твиттер чувака с крутыми pandas tricks:
    
https://mobile.twitter.com/i/moments/1158828895547854849